### PR TITLE
Kibana Elastic Search Installation via Docker Compose

### LINKED ISSUE #8: Kibana Elastic Search Installation
Create Docker file to install Kibana and Elastic search and write down relevant steps to deploy in local system and use them

### PR DESCRIPTION
**Pull request by rav94**
resolves #8

### CODE REVIEW

**Comment by DiptoChakrabarty** [comment]
Thank you for the PR ,could you also please attach an image in the ReadMe 
And also there is no  need to create a separate directory the code can be added in a Microservices/kibana_elasticsearch directory

**Comment by rav94** [comment]
@DiptoChakrabarty is it an image of Elasticsearch and Kibana running on the browser or the docker-compose up command output?

**Comment by DiptoChakrabarty** [comment]
Image of Elasticsearch and Kibana running on the browser will do @rav94

**Review by DiptoChakrabarty — APPROVED** [review]

**Comment by DiptoChakrabarty** [comment]
Thank you merged

**Comment by rav94** [comment]
@DiptoChakrabarty Thanks!  (y)

**Pull request merged**
